spring.application.name=securecapita
server.port=8081

# MySQL Connection Configuration
#spring.datasource.url=jdbc:mysql://localhost:3306/securecapita?useSSL=false&serverTimezone=UTC
spring.datasource.url=jdbc:mysql://localhost:3306/securecapita
spring.datasource.username=spring_user
spring.datasource.password=spring_password

# JPA and Hibernate Configuration
spring.jpa.database-platform=org.hibernate.dialect.MySQL8Dialect
spring.jpa.generate-ddl=true
spring.jpa.show-sql=true
spring.jpa.hibernate.ddl-auto=update

# Hibernate Additional Properties
spring.jpa.properties.hibernate.globally_quoted_identifiers=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQL8Dialect
spring.jpa.properties.hibernate.format_sql=true

# Spring SQL Initialization Mode
spring.sql.init.mode=never